Diminui retries, deixa código mais conciso

diff --git a/check_site b/check_site
--- a/check_site
+++ b/check_site
@@ -4,31 +4,30 @@ set -euo pipefail
 
 log() {
   local level="${2:-INFO}"
-  echo "$(date -Is) [$level] $1" | tee -a "$LOGFILE" $([[ $level == ERROR ]] && echo >&2 || echo >&3)
+  echo "$(date -Is) [$level] $1" | tee -a "$LOGFILE" >&$([[ $level == ERROR ]] && echo 2 || echo 3)
 }
 
-: "${WEBSITE_DB:=./websites}"
+: "${WEBSITE_DB:=./websites}" && [[ -f $WEBSITE_DB ]] || { log "Missing website database: $WEBSITE_DB" "ERROR"; exit 1; }
 : "${HOOK_URL:?}"
 : "${LOGFILE:=/var/log/check_site.log}"
 
-[[ -f $WEBSITE_DB ]] || { log "Missing website database: $WEBSITE_DB" "ERROR"; exit 1; }
-
 temp_db=$(mktemp) || { log "Failed to create temporary database file" "ERROR"; exit 1; }
+trap 'rm -f "$temp_db"' EXIT 
 
 while IFS=' ' read -r url name last_status last_timestamp; do 
   ping -c 1 8.8.8.8 &>/dev/null || { log "Network is down, skipping website checks." "ERROR"; continue}
 
-  status_code=$(curl -Is --retry 5 --max-time 20 -L -w "%{http_code}" -o /dev/null "$1")
+  status_code=$(curl -Is --retry 2 --max-time 20 -L -w "%{http_code}" -o /dev/null "$url")
   status="DOWN"
   case $? in
     0) log "Response for $name ($url): $status_code"; [[ $status_code == 200 ]] && status="UP" ;;
-    28) log "Timeout while checking $name ($url), assuming DOWN" "ERROR" ;;
+    28) log "Timeout while checking $name ($url), assuming DOWN" ;;
     *) log "Curl error $? while checking $name ($url), assuming DOWN" "ERROR" ;;
   esac
 
   if [[ $status != $last_status ]]; then 
     log "$name changed to $status"
-    [[ $status == UP ]] && message="✅ **$name** está online!" || message="❌ **$name** caiu!"
+    message=$([[ $status == UP ]] && echo "✅ **$name** está online!" || echo "❌ **$name** caiu!")
     curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"$message\"}" "$HOOK_URL"
   else 
     log "$name remains $last_status"
