Melhoria de legibilidade

diff --git a/website-monitor b/website-monitor
--- a/website-monitor
+++ b/website-monitor
@@ -7,7 +7,7 @@ trap 'rm -f $tmp_error' EXIT
 send_message() { curl -X POST -F "content=$1" "$HOOK_URL"; }
 query() {
   if ! sqlite3 monitor-db "$1"; then 
-    echo "Error while running query" >&2;
+    echo "Error while running query $1" >&2;
     exit 1;
   fi
 }
@@ -30,5 +30,9 @@ while IFS='|' read -r id url name last_status _; do
   [[ $exit_code -ne 0 ]] && cat "$tmp_error"
   [[ $status == "$last_status" ]] && continue
 
-  send_message "$(if [[ $status == UP ]]; then echo "✅ **$name** está online!"; else echo "❌ **$name** está fora do ar! 😞"; fi)"
+  if [[ $status == UP ]]; then
+    send_message "✅ **$name** está online!"
+  else
+    send_message "❌ **$name** está fora do ar! 😞"
+  fi
 done
