Adiciona banco de dados sqlite3

diff --git a/website-monitor b/website-monitor
--- a/website-monitor
+++ b/website-monitor
@@ -2,12 +2,13 @@
 : "${HOOK_URL:?}"
 send_message() { curl -X POST -F "content=$1" "$HOOK_URL"; }
 
-tmp_result=$(mktemp -t website-monitor.XXXXXX) && cp ./monitor-db "$tmp_result"
+export LC_NUMERIC=C
 tmp_error=$(mktemp -t website-monitor.XXXXXX)
 
-trap 'rm -f $tmp_error $tmp_result' EXIT
+trap 'rm -f $tmp_error' EXIT
 
-while IFS=' ' read -r url name last_status _; do 
+sqlite3 monitor-db 'SELECT * FROM Website' | \
+while IFS='|' read -r id url name last_status _; do 
   : > "$tmp_error"
 
   time=$(curl -LIsSf --retry 6 --max-time 20 "$url" -w '%{time_total}' -o /dev/null -v 2>"$tmp_error")
@@ -19,11 +20,13 @@ while IFS=' ' read -r url name last_status _; do
   esac
 
   [[ $exit_code -ne 0 ]] && cat "$tmp_error"
-  printf "[%s]\n  ↳ URL: %s\n  ↳ Status: %s (Exit: %s)\n  ↳ Response Time: %.2fs\n" \
+  printf "[%s] ↳ URL: %s ↳ Status: %s (Exit: %s) ↳ Response Time: %.2fs\n" \
   "$name" "$url" "$status" "$exit_code" "$time"
 
   [[ $status == "$last_status" ]] && continue
   send_message "$(if [[ $status == UP ]]; then echo "✅ **$name** está online!"; else echo "❌ **$name** está fora do ar! 😞"; fi)"
-  sed -i "s|$url $name $last_status .*|$url $name $status $(date -Is)|" "$tmp_result"
-done < ./monitor-db
-mv "$tmp_result" ./monitor-db
+  if ! sqlite3 monitor-db "UPDATE Website SET last_status='$status', last_checked='$(date -Is)' WHERE id=$id;" ; then 
+    echo "Couldn't update database" >&2;
+    exit 1;
+  fi
+done
