Conserta logging no banco e terminal

diff --git a/website-monitor b/website-monitor
--- a/website-monitor
+++ b/website-monitor
@@ -5,8 +5,14 @@ export LC_NUMERIC=C
 tmp_error=$(mktemp -t website-monitor.XXXXXX)
 trap 'rm -f $tmp_error' EXIT
 send_message() { curl -X POST -F "content=$1" "$HOOK_URL"; }
+query() {
+  if ! sqlite3 monitor-db "$1"; then 
+    echo "Error while running query" >&2;
+    exit 1;
+  fi
+}
 
-sqlite3 monitor-db 'SELECT * FROM Website' | \
+query 'SELECT * FROM Website' | \
 while IFS='|' read -r id url name last_status _; do 
   : > "$tmp_error"
   time=$(curl -LIsSf --retry 6 --max-time 20 "$url" -w '%{time_total}' -o /dev/null -v 2>"$tmp_error")
@@ -16,16 +22,13 @@ while IFS='|' read -r id url name last_status _; do
     22|28) status="DOWN" ;;
     *) status="$last_status" ;;
   esac
+  
+  query "UPDATE Website SET last_status='$status', last_checked='$(date -Is)' WHERE id=$id;"
+  printf "[%s] ↳ URL: %s ↳ Status: %s (Exit: %s) ↳ Response Time: %.2fs\n" \
+  "$name" "$url" "$status" "$exit_code" "$time"
 
   [[ $exit_code -ne 0 ]] && cat "$tmp_error"
   [[ $status == "$last_status" ]] && continue
 
   send_message "$(if [[ $status == UP ]]; then echo "✅ **$name** está online!"; else echo "❌ **$name** está fora do ar! 😞"; fi)"
-  if ! sqlite3 monitor-db "UPDATE Website SET last_status='$status', last_checked='$(date -Is)' WHERE id=$id;" ; then 
-    echo "Couldn't update database" >&2;
-    exit 1;
-  fi
-
-  printf "[%s] ↳ URL: %s ↳ Status: %s (Exit: %s) ↳ Response Time: %.2fs\n" \
-  "$name" "$url" "$status" "$exit_code" "$time"
 done
